### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by pymnh** [groob/finalizer#1]
Hi
can you please add a license to this project
kind regards

**Comment by pymnh** [comment]
_ping_

for context: 
I am working on packaging https://github.com/micromdm/scep, which build with this library, for debian linux distro.
debian does not include packages with unclear/unfree licenses. 

could you please add a license?

**Comment by mejo-** [comment]
Hey @groob,

as a Debian Developer I help @pymnh to package Caddy for Debian, for which your Go library `finalizer` is a dependency. Unfortunately, we're unable to package and redistribute `finalizer` due to the missing license. In fact it's illegal to redistribute it, as no licence means all rights reserved by the author.

It would be super helpful if you could license this library under an open source license. If you lack the time to do the work yourself, just tell us what license you prefer (e.g. MIT license which is used often for Go libraries, or GPLv3 for a strong copyleft) and we prepare a pull request :blush:

**Comment by groob** [comment]
Fixed!
